##########################
# scrape config for kasten
########################## 
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: k10-http-service-discovery
  namespace: kasten-io
  labels:
    release: prom
spec:
  httpSDConfigs:
    - url: http://metering-svc.kasten-io.svc.cluster.local:8000/v0/listScrapeTargets
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: k10-executor-discovery
  namespace: kasten-io
  labels:
    release: prom
spec:
  kubernetesSDConfigs:
    - role: Pod
      namespaces:
        ownNamespace: false
      selectors:
        - role: Pod
          label: "component=executor"
  relabelings:
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - sourceLabels: [__meta_kubernetes_pod_container_port_number]
      action: keep
      regex: 8\d{3}